name: Test

# test on every push and on PRs
on:
  push:
    branches: '*'
  pull_request:

env:
  YARN_CACHE_FOLDER: ~/.yarn

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
